postgresql:
  enabled: true
  image: postgres:15
  port: 5432
  database: sausage_store
  username: store
  password: storepassword
  resources:
    requests:
      cpu: "200m"
      memory: "256Mi"
    limits:
      cpu: "500m"
      memory: "1024Mi"
  persistence:
    enabled: true
    storageClass: ""
    size: 2Gi

mongodb:
  enabled: true
  image: mongo:7.0
  containerPort: 27017
  env:
    MONGO_INITDB_ROOT_USERNAME: reports
    MONGO_INITDB_ROOT_PASSWORD: reportspassword
  resources:
    requests:
      cpu: "200m"
      memory: "256Mi"
    limits:
      cpu: "500m"  # Добавили
      memory: "512Mi"
  persistence:
    enabled: true
    storageClass: "yc-network-hdd"
    size: 1Gi