replicas: 1
revisionHistoryLimit: 15
strategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 0
service:
  port: 8080
containerPort: 8080
image: korney1978/sausage-backend
tag: "latest"
imagePullPolicy: Always
resources:
  requests:
    memory: "256Mi"
    cpu: "100m"
  limits:
    memory: "512Mi"
    cpu: "1"
livenessProbe:
  httpGet:
    path: /actuator/health
    port: 8080
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3
vpa:
  enabled: true
  updateMode: "Auto"
  minAllowed:
    cpu: "50m"
    memory: "128Mi"
  maxAllowed:
    cpu: "2"
    memory: "1Gi"
env:
  postgresUri: jdbc:postgresql://postgres-service:5432/sausage-store
  postgresUser: store
  postgresPassword: storepassword
  reportPath: /logs/reports
  logPath: /logs
annotations:
  path: /actuator/prometheus
  port: "8080"
  scrape: "true"