---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-conf
data:
  postgres_uri: {{ .Values.env.postgresUri | quote }}
  postgres_user: {{ .Values.env.postgresUser | quote }}
  postgres_password: {{ .Values.env.postgresPassword | quote }}
  report_path: {{ .Values.env.reportPath | quote }}
  log_path: {{ .Values.env.logPath | quote }}
  spring.cloud.vault.enabled: "false"  # Отключаем Vault
  