name: Sausage Store Deploy

on:
  push:
    branches:
      - main

env:
  NEXUS_HELM_REPO: https://nexus.cloud-services-engineer.education-services.ru/repository/korney-sausage-store-project-sem2
  NEXUS_HELM_REPO_USER: ${{ secrets.NEXUS_HELM_REPO_USER }}
  NEXUS_HELM_REPO_PASSWORD: ${{ secrets.NEXUS_HELM_REPO_PASSWORD }}
  SAUSAGE_STORE_NAMESPACE: r-devops-magistracy-project-2sem-36310026
  KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
  VAULT_TOKEN: ${{ secrets.VAULT_TOKEN }}

jobs:
  build_and_push_to_docker_hub:
    name: Push Docker image to DockerHub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Backend to DockerHub
        uses: docker/build-push-action@v4
        with:
          context: ./backend/
          push: true
          tags: |
            korney1978/sausage-backend:${{ github.sha }}
            korney1978/sausage-backend:latest
          build-args: |
            VERSION=${{ github.sha }}

      - name: Push Frontend to DockerHub
        uses: docker/build-push-action@v4
        with:
          context: ./frontend/
          push: true
          tags: |
            korney1978/sausage-frontend:${{ github.sha }}
            korney1978/sausage-frontend:latest

      - name: Push Backend-report to DockerHub
        uses: docker/build-push-action@v4
        with:
          context: ./backend-report/
          push: true
          tags: |
            korney1978/sausage-backend-report:${{ github.sha }}
            korney1978/sausage-backend-report:latest

  add_helm_chart_to_nexus:
    name: Add Helm Chart To Nexus
    runs-on: ubuntu-latest
    needs: build_and_push_to_docker_hub
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.14.4

      - name: Package Helm Chart
        run: |
          helm package ./sausage-store-chart --version 0.1.1

      - name: Push Helm Chart to Nexus
        run: |
          curl -u ${{ env.NEXUS_HELM_REPO_USER }}:${{ env.NEXUS_HELM_REPO_PASSWORD }} \
            --upload-file sausage-store-0.1.1.tgz \
            https://nexus.cloud-services-engineer.education-services.ru/repository/korney-sausage-store-project-sem2/sausage-store-0.1.0.tgz

      - name: Upload Helm Chart Artifact
        uses: actions/upload-artifact@v4
        with:
          name: helm-chart
          path: sausage-store-0.1.1.tgz

  deploy_helm_chart_to_kubernetes:
    name: Deploy Helm Chart To Kubernetes
    runs-on: ubuntu-latest
    needs: add_helm_chart_to_nexus
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Download Helm Chart Artifact
        uses: actions/download-artifact@v4
        with:
          name: helm-chart
          path: .

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.14.4

      - name: Clear Helm Cache
        run: |
          rm -rf ~/.cache/helm
          helm env

      - name: Configure Helm repository
        run: |
          # Проверяем переменные
          echo "NEXUS_HELM_REPO: https://nexus.cloud-services-engineer.education-services.ru/repository/korney-sausage-store-project-sem2"
          # Проверяем доступность Nexus
          curl -u ${{ env.NEXUS_HELM_REPO_USER }}:${{ env.NEXUS_HELM_REPO_PASSWORD }} \
            -I https://nexus.cloud-services-engineer.education-services.ru/repository/korney-sausage-store-project-sem2/index.yaml || echo "Failed to access index.yaml"
          # Загружаем index.yaml вручную и сохраняем его в кэш Helm
          mkdir -p /home/runner/.cache/helm/repository
          curl -u ${{ env.NEXUS_HELM_REPO_USER }}:${{ env.NEXUS_HELM_REPO_PASSWORD }} \
            https://nexus.cloud-services-engineer.education-services.ru/repository/korney-sausage-store-project-sem2/index.yaml -o /home/runner/.cache/helm/repository/sausage-store-index.yaml || echo "Failed to download index.yaml to cache"
          ls -l /home/runner/.cache/helm/repository/
          cat /home/runner/.cache/helm/repository/sausage-store-index.yaml || echo "sausage-store-index.yaml not found"
          # Добавляем репозиторий с принудительной аутентификацией
          helm repo add sausage-store https://nexus.cloud-services-engineer.education-services.ru/repository/korney-sausage-store-project-sem2 \
            --username ${{ env.NEXUS_HELM_REPO_USER }} \
            --password ${{ env.NEXUS_HELM_REPO_PASSWORD }} \
            --force-update
          helm repo list || echo "Failed to list Helm repos"
          helm repo update || echo "Failed to update Helm repo"

      - name: Login to Kubernetes
        run: |
          echo "${{ env.KUBE_CONFIG }}" > kubeconfig.yaml
          # Исправляем права доступа к kubeconfig.yaml
          chmod 600 kubeconfig.yaml
          # Проверяем права доступа
          ls -l kubeconfig.yaml
          export KUBECONFIG=kubeconfig.yaml
          # Отладка: проверим содержимое kubeconfig
          cat kubeconfig.yaml
          # Отладка: проверим переменную KUBECONFIG
          echo "KUBECONFIG=$KUBECONFIG"
          # Отладка: проверим, что kubectl использует правильный контекст
          kubectl config view
          kubectl config current-context
          # Отладка: проверим подключение к кластеру
          kubectl version --client --output=yaml
          kubectl get pods -n ${{ env.SAUSAGE_STORE_NAMESPACE }} --output=name
          

      - name: Deploy with Helm from Nexus
        run: |
          # Проверяем доступные чарты в репозитории
          helm search repo sausage-store || echo "Failed to search Helm repo"
          helm upgrade --install sausage-store sausage-store/sausage-store \
            --version 0.1.1 \
            --namespace ${{ env.SAUSAGE_STORE_NAMESPACE }} \
            --kubeconfig kubeconfig.yaml \
            --username ${{ env.NEXUS_HELM_REPO_USER }} \
            --password ${{ env.NEXUS_HELM_REPO_PASSWORD }} \
            --set backend.tag=${{ github.sha }} \
            --set frontend.tag=${{ github.sha }} \
            --set backend-report.tag=${{ github.sha }}
        continue-on-error: true

      - name: Deploy with Helm from Local tgz if Nexus Fails
        run: |
          # Проверяем, что файл существует
          ls -l sausage-store-0.1.1.tgz
          helm upgrade --install sausage-store ./sausage-store-0.1.1.tgz \
            --version 0.1.1 \
            --namespace ${{ env.SAUSAGE_STORE_NAMESPACE }} \
            --kubeconfig kubeconfig.yaml \
            --set backend.tag=${{ github.sha }} \
            --set frontend.tag=${{ github.sha }} \
            --set backend-report.tag=${{ github.sha }}